In [1]:
data_file='/content/drive/MyDrive/Colab Notebooks/Data processing projects/KAG_Conversion_Data.csv'

In [3]:
import numpy as np

In [4]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [23]:
data_str = np.genfromtxt(data_file,delimiter=',',skip_header=1,dtype=str)
data_str

array([['708746', '916', '103916', ..., '1.429999948', '2', '1'],
       ['708749', '916', '103917', ..., '1.820000023', '2', '0'],
       ['708771', '916', '103920', ..., '0', '1', '0'],
       ...,
       ['1314412', '1178', '179979', ..., '40.28999949', '2', '0'],
       ['1314414', '1178', '179981', ..., '198.7100005', '8', '2'],
       ['1314415', '1178', '179982', ..., '165.6099987', '5', '2']],
      dtype='<U11')

In [5]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [6]:
xyzcampaignid=data[:,1]
print(xyzcampaignid)

[ 916.  916.  916. ... 1178. 1178. 1178.]


In [22]:
from numpy.lib.arraysetops import unique
unique_xyzcampaignid,count=unique(xyzcampaignid,return_counts=True)
print(unique_xyzcampaignid)
print(count)

[ 916.  936. 1178.]
[ 54 464 625]


In [11]:
len(unique_xyzcampaignid)

3

In [14]:
xyzcampaignid_916=xyzcampaignid[xyzcampaignid==916]
print(xyzcampaignid_916)
len(xyzcampaignid_916)

[916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916.
 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916.
 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916.
 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916. 916.]


54

In [16]:
xyzcampaignid_936=xyzcampaignid[xyzcampaignid==936]
print(xyzcampaignid_936)
len(xyzcampaignid_936)

[936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936. 936.
 936. 

464

In [17]:
xyzcampaignid_1178=xyzcampaignid[xyzcampaignid==1178]
print(xyzcampaignid_1178)
len(xyzcampaignid_1178)

[1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178.
 1178. 1178. 1178. 1178. 1178. 1178. 1178. 1178. 11

625

In [24]:
age=data_str[:,3]
print(age)

['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']


In [25]:
unique(age)

array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11')

In [26]:
spent=data[:,8]
print(spent)

[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]


In [28]:
spent.mean()

51.36065613141295

In [29]:
spent.min()

0.0

In [30]:
spent.max()

639.9499981

In [44]:
clicks=data[:,7]
print(clicks)
max_clicks=clicks.max()
print(max_clicks)

[  1.   2.   0. ...  28. 135. 114.]
421.0


In [41]:
id_maxclicks=data[clicks==421][:,0]
print(id_maxclicks)

[1121814.]


In [42]:
max_clicks_purchase=data[clicks==421][:,10]
print(max_clicks_purchase)

[13.]


In [57]:
if data[:,10].max() == max_clicks_purchase:
  print('Yes')
else:
  print('No the maximun in the dataset is', data[:,10].max())

No the maximun in the dataset is 21.0


In [53]:
approved_conversion=data[:,10]

In [54]:
ad_id_product_having_max_purchases=data[approved_conversion==21][:,0]
print(ad_id_product_having_max_purchases)

[1121104.]


In [56]:
data_str[approved_conversion==21]

array([['1121104', '1178', '144533', '30-34', 'M', '16', '2080666',
        '202', '360.1500015', '40', '21']], dtype='<U11')